export const courses = [
    {   _id: 1,
        title: "Full Stack Web Development",
        description: "Learn to build dynamic web applications using HTML, CSS, JavaScript, and backend technologies.",
        image: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/html5/html5-original.svg",
        alt: "HTML5",
    },
    {   _id: 2,
        title: "JavaScript Fundamentals",
        description: "Master the core concepts of JavaScript, the language of the web.",
        image: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/javascript/javascript-original.svg",
        alt: "JavaScript",
    },
    {   _id: 3,
        title: "MongoDB Basics",
        description: "Get started with MongoDB, a NoSQL database for modern applications.",
        image: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/mongodb/mongodb-original.svg",
        alt: "MongoDB",
    },
]